Name: Build & Push Wordsmith Images
on:
  pull_request:
    types:[labeled]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

  strategy:
    matrix:
      include:
        -name: db
          context: db
          dockerfile: db/Dockerfile
        -name: words
          context: words
          dockerfile: words/Dockerfile
        -name: web
          context: web
          dockerfile: web/Dockerfile
  env:
    REGISTRY: docker.io
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  steps:  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build & Push ${{ matrix.name }}
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/wordsmith-${{ matrix.name }}:${{ env.TAG }}