name: Build & Push Wordsmith Images

on:
  push:
  pull_request:
    types: [labeled]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: db
            context: ./db
            tag: serious/wordsmith:db
          - name: words
            context: ./words
            tag: serious/wordsmith:words
          - name: web
            context: ./web
            tag: serious/wordsmith:web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: Debug - list repo files
        run: |
          echo "===== WORKING DIRECTORY ====="
          pwd
          echo "===== FILE STRUCTURE ====="
          ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: ${{ matrix.tag }}
          no-cache: true   
